import Head from 'next/head';
import HomePage from './home';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Buddha Accessories</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script
          src='https://kit.fontawesome.com/618a331a9e.js'
          crossOrigin='anonymous'
        />
        <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet' />
      </Head>

      <main>
        <HomePage />
      </main>

      <footer className={styles.footer}>
        <p>AxiomThemes © 2022. All Rights Reserved.</p>
      </footer>
    </div>
  );
}
